image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
    - build
#    - test

build:
    stage: build
    script:
        - "dotnet build JamSoft.Helpers.sln --configuration Debug"
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - "dotnet test JamSoft.Helpers.sln --configuration Debug"
