image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
    - build

build:
    stage: build
    script:
        - "dotnet build JamSoft.Helpers.sln --configuration Debug"
    artifacts:
      paths:
        - bin/